spring.application.name=DeliverAI

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SpringDoc OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.packages-to-scan=edu.eci.ahia.controller
springdoc.paths-to-match=/**
